exp: cog1_cif10
seed : 0
train:
    model: cog1
    backbone: resnet18
    epochs: 1
    optimizer:
        name: adam
        lr: 0.0003
        weight_decay: 1.e-6
        momentum: 0
        scheduler: True
    dataset:
        name: CIFAR10
        data_dir: /data/input-ai/datasets/CIFAR-10
        img_size: 32
        norm_aug: False
        sobel_gauss_ksize: 3
        sobel_ksize: 3
        sobel_upsample: True
    batchsize: 128
    temperature: 0.5
    n_proj: 2048
    momentum:
        m_backbone: False
        m_update: 0.990
    criterion_weight: [1, 0, 0]
    save_dir: output
    save_model: 2
    num_workers: 4

eval:
    model: cog1
    backbone: resnet18
    dataset:
        name: CIFAR10
        data_dir: /data/input-ai/datasets/CIFAR-10
        classes: 10
        img_size: 32
        norm_aug: True
    epochs: 1
    batchsize: 64
    optimizer:
        name: adam
        lr: 0.0003
        weight_decay: 1.e-6
        momentum: 0
        scheduler: False
    model_path: output
    num_workers: 4

