exp: cog3_adv_sim_cif10
seed : 0
train:
    model: cog3_adv_sim
    backbone: resnet18
    epochs: 1000
    optimizer:
        name: adam
        lr: 0.0003
        weight_decay: 1.e-6
        momentum: 0
        scheduler: True
    dataset:
        name: CIFAR10
        data_dir: /data/input-ai/datasets/CIFAR-10
        img_size: 32
        norm_aug: False
        sobel_gauss_ksize: 3
        sobel_ksize: 3
        sobel_upsample: True
        transform: 'v1'
    batchsize: 256
    temperature: 0.5
    n_proj: 2048
    momentum:
        m_backbone: False
        m_update: 0.990
    loss:
        eps: 1.0
        loss_mode: ['kl']
        criterion_weight: {'sim':[1,1], 'kl':[1,1], 'hcr':[1,1], 'nce':[1,1]}
    save_dir: /data/output-ai/shruthi.gowda/ssl_cog/base
    save_model: 200
    num_workers: 0

eval:
    model: cog1
    backbone: resnet18
    dataset:
        name: CIFAR10
        data_dir: /data/input-ai/datasets/CIFAR-10
        classes: 10
        img_size: 32
        norm_aug: True
    epochs: 100
    batchsize: 64
    optimizer:
        name: adam
        lr: 0.0003
        weight_decay: 1.e-6
        momentum: 0
        scheduler: False
    model_path: /data/output-ai/shruthi.gowda/ssl_cog/base
    num_workers: 4

